language: node_js

node_js:
- '8'

script: npm test

notifications:
  email: false

after_success:
- npm run codecov
- npm run docs:generate

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs
  on:
    branch: master

addons:
  chrome: stable

dist: trusty
